### ISSUE TITLE
c++98 version

### ISSUE THREAD

**Issue by frranck** [arvidsson/bt#11]
Hello, is there an c++98 version port of the library ?

**Comment by arvidsson** [comment]
No. I prefer to use C++11, but the current functionality of the library doesn't really warrant the use of the newer features in the C++ language I think. Have you tried to compile it? Do you get a lot of errors?

**Comment by frranck** [comment]
Yeah but it doesn't work on old consoles that's a pity. I'm porting a subset of your lib [there](https://github.com/Javanaise/mrboom-libretro/tree/master/ai).
